import {
  User,
  Briefcase,
  Code,
  GraduationCap,
  Award,
  Mail,
  Github,
  Linkedin,
  Instagram,
  BookOpen,
  Star,
  ClipboardList,
  Users,
} from "lucide-react"

export const RESUME_DATA = {
  name: "Salik Uddin",
  profession: "Full Stack Developer with Strong Computer Vision Expertise",
  about: `I am a passionate Computer Science undergraduate with extensive experience in full-stack development, computer vision, and AI applications. My academic journey and professional experiences have fostered a deep interest in developing innovative technological solutions that address real-world challenges. I have consistently demonstrated strong problem-solving abilities, adaptability, and leadership through various projects and volunteer roles. My commitment to continuous learning is evidenced by my participation in hackathons, research initiatives, and industry collaborations. I am seeking to further my education through a Master's programme that will allow me to deepen my technical expertise while contributing to cutting-edge research in computer science.`,
  contact: {
    phone: "+91 9044431440",
    email: "uddinsalik@outlook.com",
  },
  socialLinks: [
    {
      name: "LinkedIn",
      url: "https://www.linkedin.com/in/salik-uddin/",
      icon: Linkedin,
      tooltip: "LinkedIn Profile",
    },
    {
      name: "GitHub",
      url: "https://github.com/salik03",
      icon: Github,
      tooltip: "GitHub Profile",
    },
    {
      name: "Codeforces",
      url: "https://codeforces.com/profile/uddinsalik03",
      icon: Code, // Using Code icon for Codeforces
      tooltip: "Codeforces Profile",
    },
    {
      name: "PyPI",
      url: "https://pypi.org/project/salik/",
      icon: BookOpen, // Using BookOpen for PyPI
      tooltip: "PyPI Project",
    },
    {
      name: "Instagram",
      url: "https://www.instagram.com/salik_._",
      icon: Instagram,
      tooltip: "Instagram Profile",
    },
  ],
  sections: [
    { id: "about", title: "about.md", icon: User },
    { id: "experience", title: "experience.ts", icon: Briefcase },
    { id: "skills", title: "skills.json", icon: Code },
    { id: "projects", title: "projects.js", icon: Star },
    { id: "education", title: "education.txt", icon: GraduationCap },
    { id: "certifications", title: "certifications.pdf", icon: ClipboardList },
    { id: "leadership", title: "leadership.sh", icon: Users },
    { id: "awards", title: "awards.log", icon: Award },
    { id: "contact", title: "contact.html", icon: Mail },
  ],
  education: [
    {
      institution: "Bennett University - The Times Group",
      location: "Greater Noida, India",
      degree: "Bachelor of Technology - Computer Science and Engineering",
      timeframe: "Sep 2021 - June 2025",
      specialization: "Cloud Computing, Minor: Innovation and Entrepreneurship",
      link: "https://bennett.digiicampus.com/publicGradesheet?id=O4YZB05Omz%2F3KS2Gk5b2cw%3D%3D",
    },
    {
      institution: "The Millennium School Lucknow",
      location: "Lucknow, India",
      degree: "Higher Secondary School Certificate - Physics, Chemistry, Mathematics",
      timeframe: "Sep 2009 - July 2021",
      grades: "Class 12: 86%, Class 10: 94%",
      link: "https://themillenniumschools.com/tmslucknow/",
    },
  ],
  experience: [
    {
      company: "FINCEPTA",
      location: "Hybrid",
      role: "Fullstack Developer Intern",
      timeframe: "Jan 2025 – Apr 2025",
      description: [
        "Architected and launched FINCEPTA's official website (https://fincepta.com/) using Next.js and Sanity, integrating dynamic financial data visualizations and SEO optimizations.",
        "Developed multiple AI-driven POCs to automate bank statement and financial PDF processing—leveraging Agno, Gemini, Ollama, and custom ML models—to streamline data extraction and classification workflows.",
      ],
      technologies: "Next.js, Sanity, Python, Agno, AdobePDFServices",
      link: "https://fincepta.com/",
    },
    {
      company: "Samsung Display Noida",
      location: "Noida, India",
      role: "Computer Vision Engineer (Consultant)",
      timeframe: "March 2024 – October 2024",
      description: [
        "Developed computer vision systems that saved 4,000 annual work hours by automating manufacturing robot calibration at 20x faster speeds.",
        "Achieved measurement precision up to 0.1mm with custom computer vision algorithms.",
        "Optimised models for edge deployment with 300ms inference time and 10MB model size.",
        "Created an automatic data annotation pipeline for efficient dataset labelling.",
      ],
      technologies: "OpenCV, TensorFlow, TFLite, CVAT, Android, Java, Python",
      link: "https://www.samsung.com/display/",
    },
    {
      company: "SCAMGUARD",
      location: "Greater Noida, India",
      role: "Fullstack Flutter Developer Intern",
      timeframe: "May 2023 – October 2023",
      description: [
        "Engineered a full-stack Flutter application with integrated AI spam detection to identify fraudulent communications.",
        "Developed a custom WebView plugin that tested downloaded files in a virtual environment for malware protection.",
        "Implemented Selenium-based verification system to protect users from phishing attacks.",
      ],
      technologies: "Flutter, TensorFlow, Selenium, Virtualisation, WebView",
      link: "https://github.com/salik03/Scamguard",
    },
    {
      company: "Spill Your Thoughts",
      location: "Delhi, India",
      role: "Technical Writing Intern",
      timeframe: "March 2023 – May 2023",
      description: [
        "Created technical documentation, user manuals, and guides on software development and emerging technologies.",
        "Conducted research and collaborated with subject matter experts to ensure technical accuracy.",
        "Developed engaging blog posts and articles on cutting-edge technologies and industry insights.",
      ],
      link: "https://www.spillyourthoughts.com/",
    },
    {
      company: "Neoverse",
      location: "Remote",
      role: "Fullstack Developer Intern",
      timeframe: "Jan 2022 – Mar 2022",
      description: [
        "Built a full-stack portfolio website using the MERN stack (MongoDB, Express.js, React, Node.js).",
        "Implemented SEO techniques to optimise website visibility and search engine ranking.",
        "Gained experience in Web3 technologies, working on a decentralised application.",
      ],
      technologies: "MERN Stack, JavaScript, HTML, CSS, Web3",
      link: "https://www.neoverse.io/",
    },
  ],
  skills: {
    programming: ["Python", "Java", "Dart", "JavaScript", "TypeScript", "C#", "C++", "Kotlin", "Swift", "Objective C"],
    frameworks: [
      "Flutter",
      "MERN Stack",
      "React Native",
      "Node.js",
      "Prisma",
      "FastAPI",
      "Flask",
      "Streamlit",
      "Selenium",
      "Unity",
    ],
    aiMl: ["TensorFlow", "TFLite", "OpenCV", "Computer Vision", "Machine Learning", "Data Analysis", "NLP"],
    devOpsCloud: ["Git", "Docker", "Kubernetes", "AWS", "Firebase", "CI/CD Pipelines"],
    frontend: ["React", "Tailwind CSS", "HTML5", "CSS3", "Figma", "UI/UX Design"],
    database: ["MongoDB", "SQL", "Prisma ORM", "Firebase Firestore"],
    softSkills: [
      "Problem Solving",
      "Technical Writing",
      "Team Leadership",
      "Client Communication",
      "Time Management",
      "Public Speaking",
    ],
  },
  projects: [
    {
      title: "Nom-Nom: Cut Calories, Not Taste",
      description: "Full-stack meal planning app with OCR and a nutrition expert chatbot.",
      techStack: "React Native, OCR, Azure, Node.js",
      purpose: "To provide a comprehensive meal planning solution.",
      features: ["OCR for food recognition", "Nutrition expert chatbot", "Meal tracking"],
      links: [{ name: "GitHub", url: "https://github.com/mach-12/NomNom" }],
      timeframe: "March 2024",
    },
    {
      title: "Nischal - Spam Protection",
      description: "End-to-end spam detection app for calls, SMS, and emails, ranked Top 5 in Kavach '23 competition.",
      techStack: "Python, KerasNLP, Flutter, AWS, FastAPI, Docker",
      purpose: "To protect users from spam communications.",
      features: ["Call spam detection", "SMS spam detection", "Email spam detection"],
      links: [{ name: "GitHub", url: "https://github.com/salik03/Kavach" }],
      timeframe: "August 2023",
    },
    {
      title: "Deepfake Detection Platform",
      description: "Full-stack solution to detect deepfakes using a dataset of 140k facial images.",
      techStack: "Python, Flask, React, TensorFlow, Docker",
      purpose: "To identify deepfake content.",
      features: ["Deepfake detection", "Large dataset utilization", "Web interface"],
      links: [{ name: "Live Site", url: "https://deep-fake-detection.vercel.app/" }],
      timeframe: "August 2024",
    },
    {
      title: "Profiloverse | Website",
      description: "Job-seeking platform offering ATS scoring, job filtering, and resume tools.",
      techStack: "Node.js, Express, Firebase, Selenium, React",
      purpose: "To assist job seekers in their application process.",
      features: ["ATS scoring", "Job filtering", "Resume tools"],
      links: [
        { name: "GitHub", url: "https://github.com/salik03/profiloverse.git" },
        { name: "Website", url: "https://profiloverse.vercel.app/" },
      ],
      timeframe: "August 2024",
    },
    {
      title: "Dak Ghar Niryat Kendra (DNK) | Website",
      description: "Platform to simplify electronic filing of Portal Bills of Export for small exporters.",
      techStack: "React, JavaScript, Python, Flask, Firebase, CSS",
      purpose: "To streamline export documentation for small businesses.",
      features: ["Electronic filing", "Portal Bills of Export management"],
      links: [
        { name: "GitHub", url: "https://github.com/salik03/dnk" },
        { name: "Website", url: "https://dnk-waaz.vercel.app/" },
      ],
      timeframe: "August 2024",
    },
    {
      title: "Career Market Analyzer",
      description: "Web scraping tool providing insights into career trends and market demands.",
      techStack: "Python, Selenium, Data Analysis",
      purpose: "To provide data-driven career insights.",
      features: ["Web scraping", "Trend analysis", "Market demand insights"],
      links: [{ name: "GitHub", url: "https://github.com/salik03/CareerMarketAnalyzer" }],
      timeframe: "2023",
    },
    {
      title: "GYRO - Decentralized Cab System",
      description: "Decentralized cab system utilizing blockchain for secure, transparent ride-sharing.",
      techStack: "Blockchain, Solidity, Ethereum, Smart Contracts",
      purpose: "To create a secure and transparent ride-sharing platform.",
      features: ["Decentralized system", "Blockchain security", "Smart contracts"],
      links: [
        {
          name: "Figma Prototype",
          url: "https://www.figma.com/proto/2OsVN3ZbhcgTw2pAOG5WdF/GYRO-USER-INTERFACE?node-id=8-202&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=33%3A6&show-proto-sidebar=1",
        },
      ],
      timeframe: "2022",
    },
    {
      title: "SuiteX - AI-Boosted Business Suite",
      description:
        "AI-enhanced business suite for team collaboration and productivity, featuring smart scheduling, automated document management, and video conferencing.",
      techStack: "Next.js, AI, NLP",
      purpose: "To enhance business productivity and collaboration.",
      features: ["Smart scheduling", "Automated document management", "Video conferencing"],
      links: [{ name: "Bento", url: "https://bento.me/suitex" }],
      timeframe: "2024",
    },
    {
      title: "Enhancing Fake News Detection Using BERT",
      description:
        "Developed a deep learning system for identifying fake news using the BERT (Bidirectional Encoder Representations from Transformers) architecture. Enhanced a pre-trained Hugging Face BERT model with customised neural network layers to accurately categorise news headlines.",
      techStack: "BERT, Deep Learning, Hugging Face",
      purpose: "To accurately detect fake news.",
      features: ["BERT architecture", "Custom neural network layers", "News headline categorization"],
      links: [
        {
          name: "Research Paper",
          url: "https://docs.google.com/document/d/1CZ7s6gePiYMPSjzPM8F97CnGa23uskVLW8NE2OsNaAY/edit?usp=sharing",
        },
      ],
      timeframe: "Unpublished Research",
    },
    {
      title: "Real-Time Speech To Sign Language Translation",
      description:
        "Conducted comprehensive analysis of contemporary speech-to-sign language translation methodologies. Leveraged Flutter's 'Text-to-Speech' capabilities for audio processing and feature extraction. Implemented recurrent neural networks (RNNs) for robust feature extraction capable of capturing both temporal and spatial patterns.",
      techStack: "Flutter, Text-to-Speech, RNNs",
      purpose: "To enable real-time speech to sign language translation.",
      features: ["Text-to-Speech", "Audio processing", "Feature extraction", "RNNs for pattern capture"],
      links: [
        {
          name: "Research Paper",
          url: "https://docs.google.com/document/d/1V2Ay9WeruQYuR-EFGt9CnUiD9lRbppEpXRPkurzBW4U/edit?usp=sharing",
        },
      ],
      timeframe: "Unpublished Research",
    },
    {
      title: "Multimodal Hate Meme Detection",
      description:
        "Conducted multimodal hate-meme classification research by integrating convolutional neural networks for image feature extraction with transformer-based text encoders. Built and annotated a novel dataset of hateful versus benign memes, designed a fusion module to merge visual and textual embeddings, and demonstrated state-of-the-art detection performance on benchmark splits.",
      techStack: "CNN, Transformers, Multimodal AI",
      purpose: "To detect hateful memes.",
      features: ["Image feature extraction", "Text encoding", "Fusion module", "Novel dataset"],
      links: [],
      timeframe: "Unpublished Research",
    },
  ],
  certifications: [
    {
      name: "Foundations of Project Management",
      issuer: "Google",
      date: "Mar 2023",
      credentialId: "DVN85R6TBL8P",
      link: "https://www.coursera.org/account/accomplishments/certificate/DVN85R6TBL8P",
    },
    {
      name: "The Bits and Bytes of Computer Networking",
      issuer: "Coursera",
      date: "Mar 2023",
      credentialId: "2ENKF4GYVTDF",
      link: "https://www.coursera.org/account/accomplishments/certificate/2ENKF4GYVTDF",
    },
    {
      name: "Software Engineering: Modeling Software Systems using UML",
      issuer: "Coursera",
      date: "Dec 2022",
      credentialId: "VM45VDWDAPCR",
      link: "https://www.coursera.org/account/accomplishments/certificate/VM45VDWDAPCR",
    },
    {
      name: "AWS Academy Graduate - AWS Academy Cloud Architecting",
      issuer: "AWS",
      date: "Nov 2022",
      credentialId: null,
      link: "https://www.credly.com/badges/e2515b6e-0fbb-4f52-bbf0-419d94239356/linked_in_profile",
    },
    {
      name: "AWS Academy Graduate - AWS Academy Cloud Foundations",
      issuer: "AWS",
      date: "Nov 2022",
      credentialId: null,
      link: "https://www.credly.com/badges/21c89b37-33c9-424e-b501-0e2e729a57b1/linked_in_profile",
    },
  ],
  leadership: [
    {
      role: "Founder and Chairperson",
      organization: "Mobilon: Mobile Technologies Club",
      timeframe: "Aug 2023 - Jun 2024",
      description: [
        "Founded and led a university club focused on mobile technology innovation and education.",
        "Organised workshops, conferences, and guest lectures to foster hands-on learning.",
        "Developed leadership, event management, and community building skills.",
        "Created opportunities for students to engage with industry experts and enhance technical skills.",
      ],
      link: "https://www.linkedin.com/in/mobilon-bu-6577b328a/",
    },
    {
      role: "Secretary",
      organization: "IEEE Women in Engineering",
      timeframe: "Aug 2022 - May 2023",
      description: [
        "Led initiatives to support and empower women in engineering fields.",
        "Coordinated events, workshops, and mentorship programmes promoting diversity in tech.",
        "Facilitated networking opportunities between students and industry professionals.",
      ],
      link: "https://www.linkedin.com/company/52124436/",
    },
    {
      role: "Junior Core Member",
      organization: "ACM, Association for Computing Machinery",
      timeframe: "Oct 2021 - Aug 2022",
      description: [
        "Contributed to planning and execution of technical events and coding competitions.",
        "Enhanced team collaboration and event coordination skills.",
        "Supported the promotion of computing knowledge and professional growth.",
      ],
      link: "https://www.linkedin.com/company/785681/",
    },
    {
      role: "Campus Ambassador",
      organization: "Tryst, IIT Delhi",
      timeframe: "Jan 2023 – Mar 2023",
      description: [
        "Promoted technical fest events through various social media platforms.",
        "Facilitated event registration and increased participation from different colleges.",
        "Utilised data analysis skills to track engagement metrics and improve promotion strategies.",
      ],
      link: "https://internshala.com/student/certificate/131289395/FE7AE9F6-BDAC-03CC-E1F7-D843B872F260",
    },
  ],
  awards: [
    {
      title: "Finalist, Kavach Cybersecurity Hackathon",
      description:
        "Selected among Top 5 teams from approximately 4,000 teams nationwide for developing an AI-powered spam detection application.",
      link: "https://kavach.mic.gov.in/",
    },
    {
      title: "Winner, Industry Hackathon",
      description:
        "Developed Nom-Nom, an innovative meal planning application that addresses real industry challenges.",
      link: "https://drive.google.com/file/d/1--DT8QrgA18ck-wR7e3SZLeUIIhfoasb/view?usp=sharing",
    },
    {
      title: "Winner, Industrial Project Showcase",
      description:
        "Created a real-time sign language recognition application converting gestures to text and vice versa.",
      link: "https://github.com/salik03/glimpse-spetext",
    },
    {
      title: "IBM watsonx Top 100 Winner",
      description: "Recognised among the top 100 participants in the IBM watsonx competition.",
      link: "https://www.ibm.com/watsonx",
    },
  ],
}
